permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: "Release notes / changes"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout main 分支
      - name: Checkout repository
        uses: actions/checkout@v4

      # ========== Firefox ==========
      - name: Get Firefox version
        id: firefox_version
        run: |
          VERSION=$(jq -r '.version' source_code/firefox/manifest.json)
          echo "FIREFOX_EXT_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Pack Firefox extension
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1.0.8
        with:
          extensionDir: 'source_code/firefox'
          zipFilePath: build/firefox/Peek_Pop-firefox-${{ env.FIREFOX_EXT_VERSION }}.zip
          zipIgnore: 'CHANGELOG.md|LICENSE|manifest_for_v3.json'

      # ========== Chromium ==========
      - name: Get Chromium version
        id: chromium_version
        run: |
          VERSION=$(jq -r '.version' source_code/chromium/manifest.json)
          echo "CHROMIUM_EXT_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Pack Chromium extension
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1.0.8
        with:
          extensionDir: 'source_code/chromium'
          zipFilePath: build/chromium/Peek_Pop-chromium-${{ env.CHROMIUM_EXT_VERSION }}.zip
          zipIgnore: 'CHANGELOG.md|LICENSE'

      # ========== Artifacts ==========
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-zips
          path: build/**/*

      # ========== GitHub Release ==========
      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.FIREFOX_EXT_VERSION }}
          name: ${{ env.FIREFOX_EXT_VERSION }}
          body: |
            ${{ github.event.inputs.release_notes }}
          draft: false
          prerelease: false
          files: |
            build/firefox/*.zip
            build/chromium/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
